### ISSUE TITLE
Bolt.Sips.Protocol failed to connect

### ISSUE THREAD

**Issue by dci-dev1** [zediogoviana/ethcule-poirot#3]
How do I correct the following error?

git clone https://github.com/zediogoviana/ethcule-poirot.git
cd ethcule-poirot/
bin/setup_docker
bin/server_docker
# get ethcule-poirot_ethcule container id
docker attach e974f83eef45. 
# compiling various files (.ex)
Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
**21:39:32.263 [error] Bolt.Sips.Protocol (#PID<0.506.0>) failed to connect: ** (Bolt.Sips.Internals.Error) connect: Unknown failure: :closed**

Thanks!!

root@c762492de40b:/app# bin/server
Erlang/OTP 25 [erts-13.1.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.14.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)>
21:25:02.303 [error] Bolt.Sips.Protocol (#PID<0.509.0>) failed to connect: ** (Bolt.Sips.Internals.Error) connect: Unknown failure: :closed

**Comment by zediogoviana** [comment]
Hey @dci-dev1 ! Thanks for opening this issue.
I have made a couple of changes in [this PR](https://github.com/zediogoviana/ethcule-poirot/pull/4), can you try the new changes on your side and check if they work?

The main change (and probably the only one) that you need to do is just commenting out the `ssl` option in the `config/config.exs` file if using a local connection to Docker. I had forgotten to leave that note in the README file.

Ping me after you've tried it out 👍

**Comment by dci-dev1** [comment]
Hi zediogoviana,

That fixed the connection issue.  Thanks.

I was able to run EthculePoirot.NetworkExplorer.explore and look at the data with neo4j browser.  Yea!!!!

However, I was not able to run the command additional times. Even if I deleted everything and started from scratch (new git clone, new containers, etc). I would get the following:

19:13:41.959 [info] Querying 0x732f15fbac21413ee4834b01b7cd31a0fb268764

19:13:42.176 [warning] Failed ETH transactions for 0x732f15fbac21413ee4834b01b7cd31a0fb268764

19:13:42.177 [info] Fully explored 0x732f15fbac21413ee4834b01b7cd31a0fb268764

I even tried a fresh install on a different computer with the same results.  No data would be queried and inserted into DB.

**Comment by zediogoviana** [comment]
Hum, when that happens, normally it's because the Blockscout API (the one I'm using to fetch transaction data) couldn't get a result in time (some queries take a lot of time). Does it work with different addresses?

I normally check against their [GraphiQl interface here](https://blockscout.com/eth/mainnet/graphiql) using 
```
{
  address(hash: "0x732f15fbac21413ee4834b01b7cd31a0fb268764") {
    transactions(first: 20) {
      edges {
      	node {
          fromAddressHash
          rest of the things...
      	}
      }
    }
  }
}
```

This is clearly a limitation of this codebase by depending on this API. It's free, so I can't fully complain, but it has some downsides. I've been exploring some alternatives like using my company's (https://github.com/finiam) Ethereum Node, but it has proven to be a bit more complicated than expected 😟

**Comment by dci-dev1** [comment]
Yeah, I tried different addresses. I figured I must of hit the limits of what a free API key will deliver in any particular time frame.  I am going to try the query again in a few days to verify that hypothesis.

Thanks for this application! It is a great start for me to explore analysis of blockchain transactions.  Thanks again!!!

**Comment by zediogoviana** [comment]
I tried running for the address you specified above, two times in a row and it worked... Maybe you got on a blocklist somehow. I thought this could be some timeout, but according to the logs you sent, the fail is almost instantaneous (while I have set a timeout limit of 2 minutes per request).

Screenshot from my console running twice:

![Screenshot 2022-11-30 at 21 31 15](https://user-images.githubusercontent.com/25623039/204912327-5e8ecbdb-fe88-434e-b6a9-856efe7fd1f8.png)

I appreciate your feedback! If you encounter any issues or want to discuss some ideas, feel free to open a new issue or a PR.

Btw, you'll probably have interest in watching [this livestream](https://youtu.be/UiBSVahMWAM) I took part with Neo4j in October, where I talk about exploring blockchain transactions using this app, and at the end, I use some Cypher Queries that you may find useful. (Kind of a shameless plug, I know 😂)

**Comment by tad3j** [comment]
Had the same issue and found out that response contained 302 error code. 

Setting `BLOCKSCOUT_API_URL` to `https://eth.blockscout.com/graphiql` solved the issue for me (seems like blockscout moved their graphiql to a subdomain and code is not following redirects...not sure why it worked on first run but then stopped though).

**Comment by zediogoviana** [comment]
Hey @tad3j! Thanks for finding that! Indeed when opening the value set under `BLOCKSCOUT_API_UR` on the browser, it redirects to that new one. 
I have updated the `.envrc.sample file 👍

**Comment by tad3j** [comment]
No problem, thank you for preparing this for us to start exploring.

Dockerfile should also be updated: https://github.com/zediogoviana/ethcule-poirot/blob/master/Dockerfile#L27
